apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: ams-cluster
  git:
    syncRepo: git@github.com:fafroz/gke-anthos-config-demo.git  
    syncBranch: main
    secretType: ssh
#     policyDir: "hello-namespace/config-root"
